global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: "my-project"

scrape_configs:
  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "^node_memory_Active_bytes"
        target_label: __tmp_keep_me
        replacement: true
      - source_labels: [__tmp_keep_me]
        regex: true
        action: keep
