version: "3.7"

networks:
  net1:

volumes:
  vmdata:

services:
  victoriametrics_tsdb:
    container_name: frigga_victoriametrics
    image: victoriametrics/victoria-metrics:v1.53.1
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    volumes:
      - vmdata:/storage
    command:
      - '--storageDataPath=/storage'
      - '--graphiteListenAddr=:2003'
      - '--opentsdbListenAddr=:4242'
      - '--httpListenAddr=:8428'
      - '--influxListenAddr=:8089'
    networks:
      - net1
    restart: always


  prometheus:
    container_name: frigga_prometheus
    image: prom/prometheus:v2.24.1
    volumes:
      - ./:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-admin-api"
      - "--web.enable-lifecycle"
    ports:
      - 9090:9090
    depends_on:
      - container-exporter
      - node-exporter
    networks:
      - net1

  node-exporter:
    container_name: frigga_node-exporter
    image: prom/node-exporter:v1.1.0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - net1

  container-exporter:
    container_name: frigga_container-exporter
    image: prom/container-exporter:latest
    volumes:
      - /sys/fs/cgroup:/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9104:9104
    networks:
      - net1

  grafana:
    container_name: frigga_grafana    
    image: grafana/grafana:7.3.7
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    depends_on:
      - container-exporter
      - prometheus
      - node-exporter
    networks:
      - net1
