global:
  evaluation_interval: 15s
  scrape_interval: 10s
  external_labels:
    monitor: frigga
remote_write:
  - url: "http://frigga_victoriametrics:8428/api/v1/write"

scrape_configs:
  - job_name: "victoriametrics"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "^flag$"
        target_label: __name__
        replacement: "vm_flag"
      - regex: ^vm_flag
        replacement: true
        source_labels: [__name__]
        target_label: __tmp_keep_me
    static_configs:
      - targets: ["frigga_victoriametrics:8428"]

  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "container-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["container-exporter:9104"]
---
name: frigga
exclude_jobs: []
