# Prometheus datasource
# # config file version
apiVersion: 1

# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
  - name: Prometheus
    version: 1
    type: prometheus
    access: proxy
    orgId: 1
    isDefault: true
    url: http://prometheus.default.svc.cluster.local:9090
    editable: false
