apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: default
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.24.1
          ports:
            - containerPort: 9090
          args:
            - "--config.file=/etc/prometheus/prometheus-original.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
            - "--web.enable-admin-api"
            - "--web.enable-lifecycle"
          volumeMounts:
            - mountPath: "/etc/prometheus/"
              name: prometheus
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      volumes:
        - name: prometheus
          hostPath:
            path: /home/docker/.frigga/kubernetes/
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: default
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:7.3.7
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: "/etc/grafana/provisioning/"
              name: provisioning
              readOnly: true
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: provisioning
          hostPath:
            path: /home/docker/.frigga/kubernetes/grafana/provisioning/
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: victoriametrics-tsdb
  namespace: default
spec:
  selector:
    app: victoriametrics-tsdb
  ports:
    - name: http
      protocol: TCP
      port: 8428
      targetPort: 8428
    - name: influx-tcp
      protocol: TCP
      port: 8089
      targetPort: 8089
    - name: influx-udp
      protocol: UDP
      port: 8089
      targetPort: 8089
    - name: graphite-tcp
      protocol: TCP
      port: 2003
      targetPort: 2003
    - name: graphite-udp
      protocol: UDP
      port: 2003
      targetPort: 2003
    - name: opentsdb-tcp
      protocol: TCP
      port: 4242
      targetPort: 4242
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoriametrics-tsdb
  namespace: default
  labels:
    app: victoriametrics-tsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics-tsdb
  template:
    metadata:
      labels:
        app: victoriametrics-tsdb
    spec:
      containers:
        - name: victoriametrics-tsdb
          image: victoriametrics/victoria-metrics:v1.53.1
          ports:
            - containerPort: 8428
            - containerPort: 8089
            - containerPort: 2003
            - containerPort: 4242
          args:
            - "--storageDataPath=/storage"
            - "--graphiteListenAddr=:2003"
            - "--opentsdbListenAddr=:4242"
            - "--httpListenAddr=:8428"
            - "--influxListenAddr=:8089"
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
