global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: "my-project"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus.default.svc.cluster.local:9090"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter.default.svc.cluster.local:9100"]
---
name: frigga
exclude_jobs: []
