name: testing
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install CLI
        run: |
          sudo apt remove python3-pip
          python -m pip install --upgrade pip
          pip install --editable .
      - name: Deploy Stack
        env:
          FRIGGA_TESTING: true
        run: bash docker-compose/deploy_stack.sh
      - name: Apply Changes
        run: bash docker-compose/run_tests.sh
